version: '2'
services:
  eureka:
    build: ./movie-eureka
    ports:
      - "8761:8761"
    networks:
      - inside
    environment:
      - JAVA_OPTS=-Xmx128m
  zuul:
    build: ./movie-zuul
    ports:
      - "8080:8080"
    links:
      - eureka
    networks:
      - inside
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx128m
  movie:
    build: ./movie-movie
    ports:
      - "8081:8080"
    networks:
      - inside
    links:
      - eureka
      - moviedb
    depends_on:
      - moviedb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx52m
  moviedb:
    image: mongo:3.4.2
    ports:
      - 27017
    networks:
      - inside
  order:
    build: ./movie-order
    ports:
      - "8083:8080"
    networks:
      - inside
    links:
      - eureka
      - orderdb
    depends_on:
      - orderdb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx52m
  orderdb:
    image: mongo:3.4.2
    ports:
      - 27017
    networks:
      - inside
  theater:
    build: ./movie-theater
    ports:
      - "8084:8080"
    networks:
      - inside
    links:
      - eureka
      - theaterdb
    depends_on:
      - theaterdb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx52m
  theaterdb:
    image: mongo:3.4.2
    ports:
      - 27017
    networks:
      - inside
  user:
    build: ./movie-user
    ports:
      - "8082:8080"
    networks:
      - inside
    links:
      - eureka
      - userdb
    depends_on:
      - userdb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx52m
  userdb:
    image: mongo:3.4.2
    ports:
      - 27017
    networks:
      - inside
networks:
  inside:
