---
- hosts: server
  vars:
    work_dir: /home/ubuntu/movie-example
  tasks:
  # - name: export env
  #   script: ./env.sh

  - name: run unit test
    shell: |
      export MGP=localhost:4000
      export PACT_URL=http://localhost:8880/      
      export DB_HOST=localhost
      export TARGET=movie
      export MOVIE_HOST=localhost         
      export MOVIE_PORT=8081
      export ORDER_HOST=localhost
      export ORDER_PORT=8083
      export THEATER_HOST=localhost
      export THEATER_PORT=8084
      export USER_HOST=localhost
      export USER_PORT=8082
      sh ./runAllTest.sh
    args:
      chdir: "{{ work_dir }}"