@startuml
hide footbox
title Pick Up Movie Tickets

actor User
participant "Order Service" as OS
participant "User Service" as US

User -> OS: Pick Up Tickets Request
activate OS

OS -> US: Check User
activate US
US --> OS: Response\nA Valid User
deactivate US

OS --> User: Pick Up Tickets Response
deactivate OS

@enduml