@startuml
left to right direction
:User: -- (Registration)
:User: -- (View Movie Details)
:User: -- (View Timetable)
:User: -- (Book Movie Tickets)
:User: -- (Check Ticket Orders)
:User: -- (Get Movie Tickets)
@enduml